### ISSUE TITLE
[Incompatibility] Crash on launch if Lithium is installed

### ISSUE THREAD

**Issue by JLUsr** [CalvinMT/PowerStones#2]
See this [Gist!](https://gist.github.com/JLUsr/6eb0d41bcb8b5830401280b8e1cae22f) I am using Minecraft 1.19.2 | Lithium 0.10.4 | PowerStones 1.1.0

**Comment by CalvinMT** [comment]
Well, I'm not surprised as Lithium optimises redstone behaviour.

As mentioned in the [readme file](https://github.com/CalvinMT/PowerStones/blob/main/README.md), this mod will break any other redstone mod without a single doubt. However, I am willing to make this mod as compatible as possible with other redstone mods, but it will take some time as I need to either find ways of how to do it or learn how to do it.

Making this mod compatible with mods which optimises redstone behaviour will require me to either change each one of these mods code, or to make the game ignore the redstone optimisation (if possible). The latter seems to me as a better solution. As this solution would disable any redstone behaviour optimisation, I guess that this mod will require its own redstone behaviour optimisation in the long run.
