### ISSUE TITLE
The basic functionality of redstone components is broken.

### ISSUE THREAD

**Issue by billyp673** [CalvinMT/PowerStones#3]
### Current Behaviour
> Components, like comparitors and repeaters, aren't getting powered directly from powersources (however, they function from dust)

### Expected Behaviour
> Components getting powered by power sources.

### Reproduction Steps
> - Place a redstone block
> - Place a comparator or repeater facing out of it
> - Observe as it isn't powered

### Version Information
> - Minecraft version: 1.19.2
> - PowerStones version: 3.0.1+1.19
> - Other mods installed: ferritecore-5.0.3-forge

![unpowered](https://github.com/CalvinMT/PowerStones/assets/64395292/ebd5b51a-a0a0-4b2a-abeb-192e37fc9aad)

**Comment by CalvinMT** [comment]
Hi!
Please forgive me for the (very) late reply.
Thank you for reporting this issue. The bug has been fixed and I will update the mod with the fix, probably by the end of the week.
